name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        default: "0.3.2-SNAPSHOT"

jobs:
  release:
    name: "Build and Publish Artifact"
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          targets: 'JDK11_HOME'
      - name: Setup Toolchain
        shell: bash
        run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>11</version>
              </provides>
              <configuration>
                <jdkHome>${{ env.JDK11_HOME }}</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          EOF
      - name: Install JDK 8 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Update Configuration
        run: |
          find . -type f -name "pom.xml" -exec sed -i -e 's|${revision}|${{ github.event.inputs.version }}|g' \
            -e 's|^\(    <version>\).*\(</version>\)$|\1${{ github.event.inputs.version }}\2|' \
            -e 's|${parent.groupId}|com.clickhouse|g' -e 's|${project.parent.groupId}|com.clickhouse|g' '{}' \;
          find . -type f -name "simplelogger.*" -exec rm -fv '{}' \;
      - name: Build
        run: |
          mvn package --batch-mode --activate-profiles release
      - name: Create Pre-release on Github
        uses: "zhicwu/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ github.event.inputs.version }}"
          prerelease: true
          title: "Release v${{ github.event.inputs.version }}"
          files: |
            LICENSE
            **/target/clickhouse*.jar
